quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/<database>
    username: <username>
    password: <password>

  http:
    port: 8080
    test-port: 8180

  swagger-ui:
    path: /swagger

  hibernate-orm:
    database:
      generation: update

  smallrye-jwt:
    enabled: true

mp:
  jwt:
    verify:
      publickey:
        location: publickey.pem
    issuer: localhost

wisegress:
  message: "Hello from Wisegress!"
