quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/<database>
    username: <username>
    password: <password>

  http:
    port: 8080

  swagger-ui:
    path: /swagger

wisegress:
  message: "Hello from Wisegress!"
